# Generated by Django 2.2.5 on 2019-09-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='categories',
            field=models.CharField(default=None, max_length=1024, null=True, verbose_name='personal categories'),
        ),
        migrations.AlterField(
            model_name='user',
            name='filter_list',
            field=models.CharField(default=None, max_length=1024, null=True, verbose_name='personal filter list'),
        ),
    ]
