#!/usr/bin/env python3
import os
import sys
import subprocess
import json

######################################Versioning check##########################################
i = None
while i != "y":
    i = input("Please make sure that all changes have been properly versioned. Hit (y) to confirm. Hit (n) to chancel.\n")
    if i =="n":
        sys.exit(1)
######################################Get secrets##########################################
with open('secret.json','r') as f:
    secret = json.load(f)
######################################Rsync command##########################################
print("Syncing to server ...\n")
cdo = f"rsync -a -v -z --progress . {secret['server_user']}@{secret['server_ip']}:~/prog/slarxiv/ --exclude venv --exclude .git --exclude .idea --exclude debug.log --exclude info.log --exclude errors.log --exclude db.sqlite3 --exclude __pycache__ --exclude secret.json --exclude secret_prod.json --exclude secret_dev.json --exclude venv_windows"
process = subprocess.Popen(cdo.split(), stdout=subprocess.PIPE)
output, error = process.communicate()



